(() => {
'use strict';
const $ = (id) => document.getElementById(id);
const STORAGE = 'folio.v2';
const BOARD_NAMES = {want:'읽고 싶어요', reading:'읽는 중', done:'다 읽었어요'};
const INTERESTS = ['소설','일과 커리어','마음과 관계','인문·사회','과학','여행','경제'];
const GOALS = ['새로운 관점','가볍게 읽기','실무에 적용','몰입하는 이야기'];
const SEEDS = [
{id:'demo:almond',title:'아몬드',author:'손원평',tags:['소설','마음과 관계'],goals:['몰입하는 이야기'],pages:264,yes24:38188003},
{id:'demo:convenience',title:'불편한 편의점',author:'김호연',tags:['소설','마음과 관계'],goals:['가볍게 읽기','몰입하는 이야기'],pages:268,yes24:99308021},
{id:'demo:fish',title:'물고기는 존재하지 않는다',author:'룰루 밀러',tags:['과학','인문·사회'],goals:['새로운 관점'],pages:300,yes24:105526047},
{id:'demo:habits',title:'아주 작은 습관의 힘',author:'제임스 클리어',tags:['일과 커리어','마음과 관계'],goals:['실무에 적용'],pages:360,yes24:69655504},
{id:'demo:dream',title:'달러구트 꿈 백화점',author:'이미예',tags:['소설'],goals:['가볍게 읽기','몰입하는 이야기'],pages:300,yes24:91065309},
{id:'demo:momo',title:'모모',author:'미하엘 엔데',tags:['소설','인문·사회'],goals:['새로운 관점','몰입하는 이야기'],pages:360,yes24:125711161},
{id:'demo:namiya',title:'나미야 잡화점의 기적',author:'히가시노 게이고',tags:['소설','마음과 관계'],goals:['몰입하는 이야기'],pages:456,yes24:116586056},
{id:'demo:sapiens',title:'사피엔스',author:'유발 하라리',tags:['인문·사회','과학'],goals:['새로운 관점'],pages:636,yes24:23030284},
{id:'demo:gene',title:'이기적 유전자',author:'리처드 도킨스',tags:['과학'],goals:['새로운 관점'],pages:632,yes24:4078717},
{id:'demo:work',title:'몰입 확장판',author:'황농문',tags:['일과 커리어','과학'],goals:['실무에 적용'],pages:320,yes24:126160327},
{id:'demo:onething',title:'원씽',author:'게리 켈러 · 제이 파파산',tags:['일과 커리어','경제'],goals:['실무에 적용'],pages:280,yes24:9349031},
{id:'demo:proof',title:'구의 증명',author:'최진영',tags:['소설','마음과 관계'],goals:['몰입하는 이야기'],pages:176,yes24:118578901},
{id:'demo:tube',title:'튜브',author:'손원평',tags:['소설','마음과 관계'],goals:['몰입하는 이야기'],pages:276,yes24:110726392},
{id:'demo:counter',title:'서른의 반격',author:'손원평',tags:['소설','일과 커리어'],goals:['몰입하는 이야기'],pages:272,yes24:53580370},
{id:'demo:dream2',title:'달러구트 꿈 백화점 2',author:'이미예',tags:['소설'],goals:['몰입하는 이야기'],pages:308,yes24:102789938},
{id:'demo:convenience2',title:'불편한 편의점 2',author:'김호연',tags:['소설'],goals:['가볍게 읽기'],pages:320,yes24:111088149},
{id:'demo:wandeuki',title:'완득이',author:'김려령',tags:['소설','마음과 관계'],goals:['몰입하는 이야기'],pages:240,yes24:2849279},
{id:'demo:jiyoung',title:'82년생 김지영',author:'조남주',tags:['소설','인문·사회'],goals:['새로운 관점'],pages:192,yes24:32972572},
{id:'demo:hagwon',title:'American Hagwon',author:'Min Jin Lee',tags:['소설','인문·사회'],goals:['몰입하는 이야기','새로운 관점'],pages:null,yes24:177762935},
{id:'demo:odyssey',title:'The Odyssey: The Complete Screenplay',author:'Christopher Nolan',tags:['소설','인문·사회'],goals:['새로운 관점'],pages:null,yes24:189094642},
{id:'demo:fear',title:'21 Days of Fear: One Day, One Letter',author:'Hervé Commère',tags:['소설'],goals:['몰입하는 이야기'],pages:424,yes24:195489930}
].map((b) => ({...b,source:'example',image:'https://image.yes24.com/goods/'+b.yes24+'/L',url:'https://www.yes24.com/product/goods/'+b.yes24,description:'직접 고른 예시 책입니다. 자세한 소개는 판매처에서 확인해 주세요.'}));
let curiosities=[],extrasFilter='all',pairIndex=0;
function read(key,fallback){try{const v=JSON.parse(localStorage.getItem(key));return v===null?fallback:v}catch{return fallback}}
function normalizeSaved(book){if(!book||!book.id||!book.title)return null;let image=book.image||null;if(!image&&book.yes24Id)image='https://image.yes24.com/goods/'+book.yes24Id+'/L';if(!image&&book.coverId)image='https://covers.openlibrary.org/b/id/'+book.coverId+'-L.jpg';return {...book,author:book.author||'저자 정보 없음',image,tags:Array.isArray(book.tags)?book.tags:[],goals:Array.isArray(book.goals)?book.goals:[],board:BOARD_NAMES[book.board]?book.board:'want'} }
function initialState(){const current=read(STORAGE,null);if(current&&Array.isArray(current.saved)){return {...current,saved:current.saved.map(normalizeSaved).filter(Boolean),ignored:Array.isArray(current.ignored)?current.ignored:[],profile:current.profile||{interests:[],goals:[],length:'any',favorite:''}}}const legacy=read('folio.savedBooks.v1',[]);const notes=read('folio.personalNotes.v1',{});return {profile:{interests:[],goals:[],length:'any',favorite:''},saved:(Array.isArray(legacy)?legacy:[]).map(normalizeSaved).filter(Boolean).map((b)=>({...b,note:notes[b.id]||''})),ignored:[]}}
const state=initialState();let currentBooks=SEEDS.slice(),currentPage=0,currentView='discover',currentBoard=Object.keys(BOARD_NAMES).find((key)=>state.saved.some((book)=>book.board===key))||'want',currentFilter='all',currentQuery='',currentSource='curated',requestSerial=0,toastTimer=0;
function persist(){try{localStorage.setItem(STORAGE,JSON.stringify(state))}catch{toast('저장 공간에 기록하지 못했습니다.')}}
function clean(s){return String(s||'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function safeUrl(s){return /^https:\/\//.test(String(s||''))?s:'#'}
function safeImage(s){return /^https:\/\//.test(String(s||''))?s:null}
function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2400)}
function savedBook(id){return state.saved.find((b)=>b.id===id)}
function anySignal(){const p=state.profile;return !!(p.interests.length||p.goals.length||p.favorite.trim()||p.length!=='any'||state.saved.length)}
function matchTags(book){const hay=[book.title,book.author,book.description,...(book.tags||[])].join(' ').toLowerCase();return INTERESTS.filter((tag)=>{if(tag==='소설')return (book.tags||[]).includes(tag)||/novel|fiction|문학|소설/i.test(hay);if(tag==='일과 커리어')return /business|career|work|management|일|커리어|경영|습관/i.test(hay);if(tag==='마음과 관계')return /psychology|relationship|마음|관계|심리/i.test(hay);if(tag==='인문·사회')return /history|society|social|philosophy|인문|사회|역사/i.test(hay);if(tag==='과학')return /science|biology|과학|생물/i.test(hay);if(tag==='여행')return /travel|journey|여행/i.test(hay);return /economics|finance|money|경제|금융/i.test(hay)})}
function score(book){const p=state.profile;let value=0,reasons=[];const tags=matchTags(book);const matched=p.interests.filter((x)=>tags.includes(x));if(matched.length){value+=matched.length*5;reasons.push('관심 주제: '+matched.slice(0,2).join(', '))}const titleText=(book.title+' '+book.author).toLowerCase();if(p.favorite.trim()&&titleText.includes(p.favorite.trim().toLowerCase())){value+=7;reasons.push('좋아하는 책·작가와 관련')}const savedAuthors=state.saved.map((b)=>b.author).filter(Boolean);if(savedAuthors.includes(book.author)){value+=4;reasons.push('저장한 책과 같은 작가')}const savedTags=new Set(state.saved.flatMap((b)=>matchTags(b)));if(tags.some((t)=>savedTags.has(t))){value+=2;reasons.push('저장한 책과 비슷한 주제')}const goalMatches=p.goals.filter((g)=>(book.goals||[]).includes(g));if(goalMatches.length){value+=3;reasons.push('읽는 목적: '+goalMatches[0])}if(p.length==='short'&&book.pages&&book.pages<=300){value+=2;reasons.push('짧게 읽기 좋은 분량')}if(p.length==='long'&&book.pages&&book.pages>=350){value+=2;reasons.push('깊게 읽을 분량')}return {value,reason:reasons[0]||''}}
function uniqueBooks(books){const seen=new Set();return books.filter((b)=>{const key=(b.title+'|'+b.author).toLowerCase().replace(/\s/g,'');if(!b.title||seen.has(key))return false;seen.add(key);return true})}
function refineSearch(books,query){const needle=query.toLowerCase().replace(/\s+/g,' ').trim();const derived=/summary|workbook|journal|tracker|study guide|요약|해설|워크북/i;let matched=books.filter((b)=>{const title=b.title.toLowerCase().replace(/\s+/g,' '),author=b.author.toLowerCase();return title.includes(needle)||author.includes(needle)});if(!derived.test(needle))matched=matched.filter((b)=>!derived.test(b.title));if(!matched.length)matched=books.slice();const covered=matched.filter((b)=>b.image&&b.author!=='저자 정보 없음');if(covered.length)matched=covered;matched.sort((a,b)=>{const rank=(book)=>{const title=book.title.toLowerCase().replace(/\s+/g,' ');return (title===needle?10:title.startsWith(needle)?5:0)+(book.image?2:0)+(book.pages?1:0)};return rank(b)-rank(a)});const seen=new Set();return matched.filter((b)=>{const key=b.title.toLowerCase().replace(/\s+/g,' ').trim();if(seen.has(key))return false;seen.add(key);return true}).slice(0,24)}
function ranked(books){let entries=uniqueBooks(books).filter((b)=>!savedBook(b.id)&&!state.ignored.includes(b.id)).map((book,index)=>({book,index,rank:score(book)}));if(currentFilter==='recommended')entries=entries.filter((e)=>e.rank.value>0);if(currentFilter!=='recent'&&anySignal())entries.sort((a,b)=>b.rank.value-a.rank.value||a.index-b.index);return entries}
function cover(book){const image=safeImage(book.image);if(image)return '<img src="'+clean(image)+'" alt="'+clean(book.title)+' 표지" loading="lazy" referrerpolicy="no-referrer" onerror="this.style.display=\'none\';this.nextElementSibling.hidden=false"><span class="cover-placeholder" hidden>'+clean(book.title)+'<small>FOLIO</small></span>';return '<span class="cover-placeholder">'+clean(book.title)+'<small>FOLIO</small></span>'}
function card(book,rank){const saved=!!savedBook(book.id);return '<article class="book-card"><div class="cover-wrap">'+cover(book)+'<button class="quick-save '+(saved?'saved':'')+'" type="button" data-save="'+clean(book.id)+'" aria-label="'+clean(book.title)+' '+(saved?'보드에서 보기':'읽고 싶어요에 저장')+'">'+(saved?'저장됨':'저장 +')+'</button></div><button class="book-open" type="button" data-open="'+clean(book.id)+'"><strong>'+clean(book.title)+'</strong><span>'+clean(book.author)+'</span></button>'+(rank&&rank.reason?'<p class="reason">'+clean(rank.reason)+'</p>':'')+'<p class="source">'+({google:'Google Books',openlibrary:'Open Library',example:'FOLIO PICK'}[book.source]||'저장된 책')+'</p></article>'}
function renderFeed(){const entries=ranked(currentBooks);const count=(currentPage+1)*12;$('bookGrid').innerHTML=entries.length?entries.slice(0,count).map((e)=>card(e.book,e.rank)).join(''):'<div class="empty">조건에 맞는 책이 아직 없어요. 주제를 바꾸거나 다른 제목을 검색해 보세요.</div>';$('moreButton').hidden=entries.length<=count;$('feedTitle').textContent=currentQuery?'Search: '+currentQuery:anySignal()?'Picked for you.':'Find your next read.';$('feedSubtitle').textContent=currentQuery?'검색어와 가까운 책을 먼저 보여줍니다.':anySignal()?'관심사와 저장한 책을 바탕으로 순서를 정했습니다.':'관심사와 읽는 목적을 고르면 추천 이유가 생깁니다.';$('feedStatus').textContent=({curated:'folio가 고른 첫 서가',google:'Google Books에서 찾은 책',openlibrary:'Google Books 연결 불가 · Open Library 검색 결과',example:'외부 검색 연결 불가 · 예시 책'}[currentSource]||'folio가 고른 책')+' · '+entries.length+'권';document.querySelectorAll('#feedFilters .chip').forEach((b)=>b.classList.toggle('selected',b.dataset.filter===currentFilter))}
function renderBoards(){if(currentBoard.startsWith('topic:')&&!state.saved.some((b)=>matchTags(b).includes(currentBoard.slice(6))))currentBoard='want';const counts=new Map(),authors=new Map();for(const book of state.saved){for(const tag of matchTags(book))counts.set(tag,(counts.get(tag)||0)+1);if(book.author&&book.author!=='저자 정보 없음')authors.set(book.author,(authors.get(book.author)||0)+1)}const topTags=[...counts].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0],'ko')).slice(0,3);const topAuthor=[...authors].sort((a,b)=>b[1]-a[1])[0];$('libraryStats').innerHTML='<div><strong>'+state.saved.length+'</strong><span>모아둔 책</span></div><div><strong>'+state.saved.filter((b)=>b.board==='reading').length+'</strong><span>지금 읽는 책</span></div><div><strong>'+clean(topTags[0]?.[0]||'아직 없음')+'</strong><span>가장 많이 모은 주제</span></div><div><strong>'+clean(topAuthor?.[0]||'아직 없음')+'</strong><span>가장 많이 모은 작가</span></div>';$('curationGrid').innerHTML=topTags.length?topTags.map(([tag,count])=>{const books=state.saved.filter((b)=>matchTags(b).includes(tag)).slice(0,3);return '<button class="curation-card" type="button" data-curation="'+clean(tag)+'"><span class="eyebrow">YOUR TOPIC SHELF</span><strong>'+clean(tag)+'</strong><small>'+count+'권을 모았어요 · 서가 열기 ↗</small><span class="curation-stack">'+books.map((b)=>safeImage(b.image)?'<img src="'+clean(b.image)+'" alt="" loading="lazy">':'<i aria-hidden="true"></i>').join('')+'</span></button>'}).join(''):'<div class="curation-empty">아직 묶을 책이 없어요. 발견 화면에서 첫 책을 저장하면 주제별 서가가 만들어집니다.</div>';let html='';for(const key of Object.keys(BOARD_NAMES)){const count=state.saved.filter((b)=>b.board===key).length;html+='<button type="button" data-board-tab="'+key+'" class="'+(currentBoard===key?'active':'')+'">'+BOARD_NAMES[key]+' <span>'+count+'</span></button>'}if(currentBoard.startsWith('topic:'))html+='<button type="button" class="topic-tab active" aria-current="true">'+clean(currentBoard.slice(6))+' 모음</button>';$('boardTabs').innerHTML=html;const books=currentBoard.startsWith('topic:')?state.saved.filter((b)=>matchTags(b).includes(currentBoard.slice(6))):state.saved.filter((b)=>b.board===currentBoard);$('boardGrid').innerHTML=books.length?books.map((b)=>card(b,null)).join(''):'<div class="empty">아직 이 서가에 책이 없습니다. 발견 화면에서 마음에 드는 책을 저장해 보세요.</div>';$('savedCount').textContent=state.saved.length}
function renderPair(){const goods=curiosities.filter((item)=>item.type==='goods');if(!goods.length){$('extrasPair').hidden=true;return}const books=state.saved.length?state.saved:SEEDS.slice(0,4);const book=books[pairIndex%books.length],item=goods[pairIndex%goods.length];$('extrasPair').hidden=false;$('extrasPair').innerHTML='<div><span class="eyebrow">A READING PAIR · FOLIO PICK</span><h2>이번 읽기 조합</h2><p>책 <strong>'+clean(book.title)+'</strong> 옆에 <strong>'+clean(item.title)+'</strong>. 읽는 시간을 위한 작은 조합입니다.</p><small>저장한 책이 있으면 그 책에서 고릅니다. 조합은 편집 제안이며 상품 간 공식 연관은 없습니다.</small></div><div class="pair-images">'+cover(book)+'<span aria-hidden="true">＋</span><img src="'+clean(item.image)+'" alt="'+clean(item.title)+' 사진" onerror="this.hidden=true"></div>'}
function renderMagazines(){const list=curiosities.filter((item)=>extrasFilter==='all'||item.type===extrasFilter);$('magazineGrid').innerHTML=list.length?list.map((m)=>'<article class="mag-card"><div class="mag-photo"><img src="'+clean(safeImage(m.image)||'')+'" alt="'+clean(m.title)+' '+clean(m.photoType)+'" loading="lazy" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><span class="fallback" hidden>사진을 불러오지 못했습니다</span></div><div class="mag-copy"><span class="retailer">'+clean(m.retailer)+' · '+clean(m.photoType)+'</span><h2>'+clean(m.title)+'</h2><p>'+clean(m.type==='bonus'?'확인된 부록: '+m.detail:m.detail)+'</p><a href="'+clean(safeUrl(m.url))+'" target="_blank" rel="noopener noreferrer">'+(m.type==='bonus'?'상품·부록 확인':'상품 확인')+' ↗</a> · <a href="'+clean(safeUrl(m.photoSource))+'" target="_blank" rel="noopener noreferrer">사진 출처 ↗</a><small>마지막 확인 '+clean(m.checkedAt)+'</small></div></article>').join(''):'<div class="empty">이 종류의 상품은 아직 없습니다.</div>';renderPair()}
async function loadCuriosities(){try{const response=await fetch('./curiosities.json',{cache:'no-store'});if(!response.ok)throw Error('HTTP '+response.status);const data=await response.json();if(!Array.isArray(data.items))throw Error('상품 목록 형식 오류');curiosities=data.items.filter((item)=>item&&['goods','bonus'].includes(item.type)&&item.title&&item.url);$('extrasStatus').textContent='편집 목록 마지막 갱신 '+(data.updatedAt||'날짜 미상')+' · 실시간 재고 정보는 아닙니다.'}catch(error){$('extrasStatus').textContent='상품 목록을 불러오지 못했습니다. 잠시 뒤 새로고침해 주세요.';console.info('Curiosities unavailable:',error.message)}renderMagazines()}
function view(name){currentView=name;document.querySelectorAll('.view').forEach((v)=>v.hidden=v.id!==name+'View');document.querySelectorAll('.nav').forEach((b)=>{b.classList.toggle('active',b.dataset.view===name);if(b.dataset.view===name)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});if(name==='boards')renderBoards();if(name==='magazines')renderMagazines();scrollTo({top:0,behavior:'smooth'})}
function renderProfile(){for(const [id,options,selected] of [['interestChips',INTERESTS,state.profile.interests],['goalChips',GOALS,state.profile.goals]]){$(id).innerHTML=options.map((x)=>'<button class="chip '+(selected.includes(x)?'selected':'')+'" type="button" data-'+(id==='interestChips'?'interest':'goal')+'="'+clean(x)+'" aria-pressed="'+selected.includes(x)+'">'+clean(x)+'</button>').join('')}$('lengthSelect').value=state.profile.length;$('favoriteInput').value=state.profile.favorite}
function normalizeGoogle(item){const v=item.volumeInfo||{};return {id:'google:'+item.id,title:v.title||'',author:(v.authors||[]).join(', ')||'저자 정보 없음',description:v.description||'',tags:v.categories||[],goals:[],pages:v.pageCount||null,image:(v.imageLinks&& (v.imageLinks.thumbnail||v.imageLinks.smallThumbnail)||'').replace(/^http:/,'https:'),url:(v.infoLink||'https://books.google.com/').replace(/^http:/,'https:'),source:'google'}}
function normalizeOpen(item){return {id:'open:'+item.key,title:item.title||'',author:(item.author_name||[]).slice(0,2).join(', ')||'저자 정보 없음',description:'',tags:(item.subject||[]).slice(0,8),goals:[],pages:item.number_of_pages_median||null,image:item.cover_i?'https://covers.openlibrary.org/b/id/'+item.cover_i+'-L.jpg?default=false':null,url:'https://openlibrary.org'+item.key,source:'openlibrary'}}
async function fetchJson(url){const ctl=new AbortController();const timer=setTimeout(()=>ctl.abort(),6000);try{const response=await fetch(url,{signal:ctl.signal});if(!response.ok)throw Error('HTTP '+response.status);return await response.json()}finally{clearTimeout(timer)}}
async function searchRemote(query){const q=encodeURIComponent(query);try{const data=await fetchJson('https://www.googleapis.com/books/v1/volumes?q='+q+'&printType=books&maxResults=40');const books=(data.items||[]).map(normalizeGoogle).filter((b)=>b.title);if(books.length)return {books,source:'google'}}catch(e){console.info('Google Books unavailable:',e.message)}try{const data=await fetchJson('https://openlibrary.org/search.json?q='+q+'&limit=40&fields=key,title,author_name,cover_i,number_of_pages_median,subject');const books=(data.docs||[]).map(normalizeOpen).filter((b)=>b.title);if(books.length)return {books,source:'openlibrary'}}catch(e){console.info('Open Library unavailable:',e.message)}return {books:[],source:'example'}}
function candidateQuery(){const p=state.profile;if(p.favorite.trim())return p.favorite.trim();const keywords={'소설':'fiction','일과 커리어':'career','마음과 관계':'psychology','인문·사회':'social science','과학':'science','여행':'travel','경제':'finance'};if(p.interests.length)return p.interests.slice(0,2).map((tag)=>keywords[tag]||tag).join(' OR ');if(state.saved.length)return state.saved[0].author;if(p.goals.includes('실무에 적용'))return 'business';if(p.goals.includes('새로운 관점'))return 'ideas';return 'books'}
async function loadBooks(query){const serial=++requestSerial;currentQuery=query||'';if(!currentQuery&&!anySignal()){currentBooks=SEEDS.slice();currentSource='curated';currentPage=0;renderFeed();return}$('feedStatus').textContent='책을 찾고 있습니다…';let result=await searchRemote(query||candidateQuery());if(serial!==requestSerial)return;const examples=currentQuery?SEEDS.filter((b)=>(b.title+' '+b.author+' '+b.tags.join(' ')).toLowerCase().includes(currentQuery.toLowerCase())):SEEDS.slice();if(result.books.length){currentBooks=uniqueBooks([...examples,...(currentQuery?refineSearch(result.books,currentQuery):result.books)]);currentSource=result.source}else{currentBooks=examples;currentSource='example'}currentPage=0;renderFeed()}
function save(book,board){if(savedBook(book.id)){const item=savedBook(book.id);item.board=board||item.board;toast('보드를 변경했습니다.')}else{state.saved.push({...book,board:board||'want'});toast('읽고 싶어요 보드에 저장했습니다.')}persist();renderFeed();renderBoards()}
function remove(id){state.saved=state.saved.filter((b)=>b.id!==id);persist();renderFeed();renderBoards();toast('보드에서 삭제했습니다.')}
function related(book){const pool=uniqueBooks([...currentBooks,...SEEDS,...state.saved]);const tags=matchTags(book);return pool.filter((b)=>b.id!==book.id&&!savedBook(b.id)&&!state.ignored.includes(b.id)).map((b)=>({b,n:(b.author===book.author?5:0)+matchTags(b).filter((t)=>tags.includes(t)).length*2})).filter((x)=>x.n>0).sort((a,b)=>b.n-a.n).slice(0,4).map((x)=>x.b)}
function findBook(id){return [...state.saved,...currentBooks,...SEEDS].find((b)=>b.id===id)}
function openBook(id){const book=findBook(id);if(!book)return;const current=savedBook(id);const relatedBooks=related(book);$('dialogBody').innerHTML='<div class="dialog-layout"><div>'+cover(book).replace('<span class="cover-placeholder"','<span class="cover-placeholder dialog-cover"').replace('<img ','<img class="dialog-cover" ')+'</div><div class="dialog-copy"><span class="eyebrow">'+clean(({google:'GOOGLE BOOKS',openlibrary:'OPEN LIBRARY',example:'EXAMPLE BOOK'}[book.source]||'SAVED BOOK'))+'</span><h2>'+clean(book.title)+'</h2><p>'+clean(book.author)+(book.pages?' · 약 '+book.pages+'쪽':'')+'</p><p class="description">'+clean(book.description||'책 소개 정보가 없습니다. 링크에서 자세한 내용을 확인해 주세요.').replace(/<[^>]*>/g,'')+'</p><div class="dialog-actions">'+Object.keys(BOARD_NAMES).map((key)=>'<button type="button" data-move="'+clean(book.id)+'" data-to="'+key+'" class="'+(current&&current.board===key?'active':'')+'">'+BOARD_NAMES[key]+'</button>').join('')+(current?'<button type="button" data-remove="'+clean(book.id)+'">보드에서 삭제</button>':'<button type="button" data-ignore="'+clean(book.id)+'">관심 없음</button>')+'<a href="'+clean(safeUrl(book.url))+'" target="_blank" rel="noopener noreferrer">책 정보 보기 ↗</a></div>'+(current?'<label class="field-label" for="bookNote">나만의 한 줄</label><textarea id="bookNote" data-note="'+clean(book.id)+'" maxlength="500" placeholder="읽고 싶은 이유나 기억할 문장을 적어보세요">'+clean(current.note||'')+'</textarea>':'')+'<p class="related-head">이 책에서 이어보기</p><div class="related-list">'+(relatedBooks.length?relatedBooks.map((b)=>'<button type="button" data-open="'+clean(b.id)+'">'+clean(b.title)+'<br><small>'+clean(b.author)+'</small></button>').join(''):'<span>같은 작가·주제의 책을 찾지 못했습니다.</span>')+'</div></div></div>';if(!$('bookDialog').open)$('bookDialog').showModal()}
function selectChip(type,value){const list=type==='interest'?state.profile.interests:state.profile.goals;const index=list.indexOf(value);if(index<0)list.push(value);else list.splice(index,1);persist();renderProfile();renderFeed()}
document.addEventListener('click',(event)=>{const target=event.target.closest('button');if(!target)return;if(target.dataset.view){view(target.dataset.view);return}if(target.dataset.extraFilter){extrasFilter=target.dataset.extraFilter;document.querySelectorAll('[data-extra-filter]').forEach((button)=>{const active=button.dataset.extraFilter===extrasFilter;button.classList.toggle('selected',active);button.setAttribute('aria-pressed',active)});renderMagazines();return}if(target.dataset.interest){selectChip('interest',target.dataset.interest);return}if(target.dataset.goal){selectChip('goal',target.dataset.goal);return}if(target.dataset.filter){currentFilter=target.dataset.filter;currentPage=0;renderFeed();return}if(target.dataset.boardTab){currentBoard=target.dataset.boardTab;renderBoards();return}if(target.dataset.curation){currentBoard='topic:'+target.dataset.curation;renderBoards();$('boardTabs').scrollIntoView({behavior:'smooth',block:'start'});return}if(target.dataset.save){const b=findBook(target.dataset.save);if(savedBook(target.dataset.save)){currentBoard=savedBook(target.dataset.save).board;view('boards')}else if(b)save(b,'want');return}if(target.dataset.open){openBook(target.dataset.open);return}if(target.dataset.move){const b=findBook(target.dataset.move);if(b){currentBoard=target.dataset.to;save(b,target.dataset.to);openBook(b.id)}return}if(target.dataset.remove){remove(target.dataset.remove);$('bookDialog').close();return}if(target.dataset.ignore){state.ignored.push(target.dataset.ignore);persist();$('bookDialog').close();renderFeed();toast('앞으로 추천에서 제외합니다.');return}});
$('profileForm').addEventListener('submit',(event)=>{event.preventDefault();state.profile.length=$('lengthSelect').value;state.profile.favorite=$('favoriteInput').value.trim();persist();currentFilter='all';loadBooks('');toast('취향을 반영해 책을 찾습니다.')});
$('searchForm').addEventListener('submit',(event)=>{event.preventDefault();const q=$('searchInput').value.trim();if(!q)return;currentFilter='all';loadBooks(q)});
$('refreshButton').addEventListener('click',()=>{currentFilter='all';$('searchInput').value='';loadBooks('')});
$('moreButton').addEventListener('click',()=>{currentPage++;renderFeed()});
$('pairAgain').addEventListener('click',()=>{pairIndex++;renderPair()});
$('dialogClose').addEventListener('click',()=>$('bookDialog').close());
$('bookDialog').addEventListener('click',(e)=>{if(e.target===$('bookDialog'))$('bookDialog').close()});
$('dialogBody').addEventListener('input',(event)=>{if(event.target.dataset.note){const b=savedBook(event.target.dataset.note);if(b){b.note=event.target.value;persist()}}});
renderProfile();renderBoards();renderFeed();loadCuriosities();loadBooks('');
})();
