(() => {
'use strict';
const app=window.folioApp;
const config=window.FOLIO_AUTH_CONFIG||{};
const login=document.getElementById('googleSignIn');
const logout=document.getElementById('googleSignOut');
const name=document.getElementById('accountName');
const bar=document.getElementById('accountBar');
const status=document.getElementById('accountStatus');
const importButton=document.getElementById('importGuest');
const retryButton=document.getElementById('retrySync');
let client=null,activeUser=null,guest=app.snapshot(),generation=0,queued=null,saving=false,timer=0,lastSaveFailed=false;
function message(value){bar.hidden=false;status.textContent=value}
function setControls(){const signed=!!activeUser;login.hidden=signed;logout.hidden=!signed;name.hidden=!signed;name.textContent=signed?(activeUser.email||'내 계정'):'';importButton.hidden=!signed||!guest.saved.length;retryButton.hidden=!signed||!lastSaveFailed}
function loadLibrary(data){app.replaceState(data&&typeof data==='object'?data:app.blankState())}
function loadSdk(){return new Promise((resolve,reject)=>{if(window.supabase){resolve(window.supabase);return}const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';script.onload=()=>window.supabase?resolve(window.supabase):reject(Error('SDK가 준비되지 않았습니다.'));script.onerror=()=>reject(Error('로그인 라이브러리를 불러오지 못했습니다.'));document.head.append(script)})}
async function flush(){if(saving||!queued||!activeUser)return !lastSaveFailed;clearTimeout(timer);const payload=queued;queued=null;const owner=activeUser.id,turn=generation;saving=true;message('계정 책장을 저장하고 있습니다…');let error;try{({error}=await client.from('folio_libraries').upsert({user_id:owner,payload,updated_at:new Date().toISOString()},{onConflict:'user_id'}))}catch(cause){error=cause}saving=false;if(turn!==generation||activeUser?.id!==owner)return false;if(error){queued=queued||payload;lastSaveFailed=true;message('계정 저장에 실패했습니다. 다시 시도할 수 있습니다.');retryButton.hidden=false;return false}lastSaveFailed=false;retryButton.hidden=true;if(queued){void flush();return true}message('계정 책장이 저장됐습니다.');return true}
function scheduleSave(payload){if(!activeUser)return;queued=payload;lastSaveFailed=false;retryButton.hidden=true;message('변경 내용을 계정에 저장할 준비 중입니다…');clearTimeout(timer);timer=setTimeout(()=>{void flush()},500)}
async function activate(user){if(activeUser?.id===user.id)return;const turn=++generation;app.setAccountSaveHandler(null);queued=null;clearTimeout(timer);message('계정 책장을 불러오는 중입니다…');let data,error;try{({data,error}=await client.from('folio_libraries').select('payload').eq('user_id',user.id).maybeSingle())}catch(cause){error=cause}if(turn!==generation)return;if(error){message('계정 책장을 불러오지 못했습니다. 연결 설정과 데이터베이스 정책을 확인해 주세요.');return}activeUser=user;loadLibrary(data?.payload);app.setAccountSaveHandler(scheduleSave);setControls();message(data?'계정 책장을 불러왔습니다.':'새 계정 책장입니다. 이 브라우저의 책은 원할 때 가져올 수 있습니다.')}
function restoreGuest(){++generation;clearTimeout(timer);queued=null;saving=false;lastSaveFailed=false;app.setAccountSaveHandler(null);activeUser=null;loadLibrary(app.guestState());setControls();message('이 브라우저에 저장된 책장을 보고 있습니다.')}
async function readUser(){try{const {data,error}=await client.auth.getUser();if(error||!data.user){restoreGuest();return}await activate(data.user)}catch{message('로그인 상태를 확인하지 못했습니다. 새로고침해 주세요.')}}
function mergeGuest(){const account=app.snapshot(),ids=new Set(account.saved.map((book)=>book.id));for(const book of guest.saved){if(!ids.has(book.id)){account.saved.push(book);ids.add(book.id)}}const wantIds=new Set(account.saved.filter((book)=>book.board==='want').map((book)=>book.id));account.upNext=[...new Set([...(account.upNext||[]),...(guest.upNext||[])])].filter((id)=>wantIds.has(id)).slice(0,3);const collections=new Map((account.collections||[]).map((entry)=>[entry.id,entry]));for(const entry of guest.collections||[]){if(collections.has(entry.id)){const existing=collections.get(entry.id);existing.books=[...new Set([...existing.books,...entry.books])];existing.extras=[...new Set([...existing.extras,...entry.extras])]}else collections.set(entry.id,entry)}account.collections=[...collections.values()];account.ignored=[...new Set([...account.ignored,...guest.ignored])];if(!account.profile.interests.length&&!account.profile.vibes.length&&!(account.profile.careerFocus||[]).length&&!account.profile.goals.length&&!account.profile.favorite&&account.profile.length==='any')account.profile=guest.profile;return account}
login.addEventListener('click',async()=>{if(!client)return;guest=app.snapshot();login.disabled=true;message('Google 로그인 화면으로 이동합니다…');try{const {error}=await client.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+location.pathname}});if(error)throw error}catch{message('로그인을 시작하지 못했습니다. 다시 시도해 주세요.');login.disabled=false}});
logout.addEventListener('click',async()=>{if(!client||!activeUser)return;logout.disabled=true;if(queued){const saved=await flush();if(!saved){logout.disabled=false;return}}const {error}=await client.auth.signOut({scope:'local'});logout.disabled=false;if(error){message('로그아웃하지 못했습니다. 다시 시도해 주세요.');return}restoreGuest()});
importButton.addEventListener('click',()=>{if(!activeUser)return;const merged=mergeGuest();app.replaceState(merged);app.persist();importButton.hidden=true;message('이 브라우저 책장을 계정에 저장하고 있습니다…')});
retryButton.addEventListener('click',()=>{void flush()});
if(!/^https:\/\/[^/]+\.supabase\.co$/.test(config.url||'')||!config.publishableKey){login.hidden=true;bar.hidden=true;return}
loadSdk().then(async(sdk)=>{client=sdk.createClient(config.url,config.publishableKey,{auth:{flowType:'implicit',detectSessionInUrl:true,persistSession:true,autoRefreshToken:true}});login.disabled=false;setControls();client.auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT')restoreGuest();else if(event==='SIGNED_IN')setTimeout(()=>{void readUser()},0)});await readUser()}).catch(()=>{login.textContent='Google 로그인 연결 실패';message('로그인 연결을 불러오지 못했습니다. 이 브라우저 책장은 그대로 사용할 수 있습니다.')});
})();
